[package]
name = "matrix_rhal"
version = "0.0.2"
authors = ["Carlos Chacin"]
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/matrix_rhal/"
keywords = ["raspberry-pi", "matrix-creator", "matrix-voice", "matrix-labs"]
exclude = ["Makefile"]
description = "The Rust implementation of MATRIX HAL."
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nix = "0.16.1"
