[package]
name = "matrix_rhal"
version = "0.0.0"
authors = ["Hermitter"]
edition = "2018"
exclude = ["Makefile"]
description = "The Rust implementation of MATRIX HAL."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nix = "0.16.1"
