[package]
name = "matrix_rhal"
version = "0.1.0"
authors = ["Hermitter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nix = "0.16.1"
libc = "0.2.66"
