[package]
name = "matrix_rhal"
version = "0.1.0"
authors = ["Hermitter <cchai013@fiu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nix = "0.16.1"

[dev-dependencies]
async-std = "1.5.0"
